language: node_js
sudo: false
node_js:
  - 8
env:
  - NODE_ENV=TEST
install:
  - 'npm install'
script:
  - npm run lint
  - npm run test
  - npm run build
  - if [[ $TRAVIS_BRANCH == 'release' ]] ; then echo npm run release; fi
before_deploy:
  - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - export TRAVIS_TAG="v.$PACKAGE_VERSION"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  - provider: releases
    email: lamhieu.vk@gmail.com
    api_key: $GITHUB_TOKEN
    on:
      condition: $TRAVIS_BRANCH =~ ^release$
      all_branches: true
      tag: true
  - provider: npm
    email: lamhieu.vk@gmail.com
    api_key: $NPM_TOKEN
    on:
      condition: $TRAVIS_BRANCH =~ ^release$
      all_branches: true
      tag: true
notifications:
  email:
    recipients:
    - lamhieu.vk@gmail.com
    on_success: change
    on_failure: always
