language: node_js
sudo: false
node_js:
  - 8
env:
  - NODE_ENV=TEST
install:
  - 'npm install'
script:
  - 'npm run verify'
  - if [[ $TRAVIS_BRANCH == 'release' ]] ; then echo npm run release; fi
after_success:
  - if [[ $TRAVIS_BRANCH == 'release' ]] ; then echo git add . && git push --follow-tags origin master; fi
before_deploy:
  - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - export TRAVIS_TAG="v.$PACKAGE_VERSION"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  - provider: releases
    email: lamhieu.vk@gmail.com
    api_key: $GITHUB_TOKEN
    on:
      tag: true
      branches:
        only:
        - release
  - provider: npm
    email: lamhieu.vk@gmail.com
    api_key: $NPM_TOKEN
    on:
      tag: true
      branches:
        only:
        - release
notifications:
  email:
    recipients:
    - lamhieu.vk@gmail.com
    on_success: change
    on_failure: always
